# -*- coding: utf-8 -*-
"""TuVaAnh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uSOcdrMN-OujWe_8ScHvQQYjZ3On-5ff
"""

from google.colab import drive
drive.mount('/content/drive')

"""# Cài đặt Python"""

pip install opencv-contrib-python

import sys
sys.version

"""# Cài đặt thư viện Fast Fourier Transform"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# sudo apt-get install libfftw3-dev libfftw3-doc

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Code/mlfw/
# #unzip pyleargist-python3-master.zip
# cd pyleargist-python3-master
# python setup.py install

"""# Kết nối tới gói phần mềm mlfw và chạy thử nghiệm

"""

!pip install filetype

import re

file_path = '/content/drive/MyDrive/Code/mlfw/helpers.py'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace('import imghdr', 'import filetype')

content = re.sub(r'imghdr\.what\(([^\)]+)\)', r'(filetype.guess_extension(Q) or "")'.replace('Q', r'1'), content)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/drive/MyDrive/Code/mlfw/
# python runner.py